routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
})->name('dashboard');

// Web
Route::group(['namespace' => 'Web', 'as' => 'web.'], function() {
	// Logged in
	Route::group(['middleware' => 'auth'], function() {
		Route::get('binary', 'BinaryController@show')->name('binary');
	});
});
	
Route::group(['namespace' => 'Auth'], function() {
	Route::post('login', 'AuthController@login')->name('login');
	Route::get('logout', 'AuthController@logout')->name('logout');
});

// Webview
Route::group(['namespace' => 'Webview', 'prefix' => 'webview', 'as' => 'webview.'], function() {
	Route::get('password/reset/{token}', 'ResetPasswordController@resetPage')->name('reset.password.page');
	Route::post('password/reset', 'ResetPasswordController@reset')->name('reset.password');

	Route::get('terms-conditions', 'AboutAppController@termsConditions')->name('terms-conditions');
	Route::get('privacy-policy', 'AboutAppController@privacyPolicy')->name('privacy-policy');
	Route::get('about-us', 'AboutAppController@aboutUs')->name('about-us');

	Route::get('/promo/{promo}', 'PromoController@detail')->name('promo-detail');

	// Logged in
	Route::group(['middleware' => 'auth.params'], function() {
		Route::get('binary', 'BinaryController@show')->name('binary');
		Route::get('user', 'AboutAppController@user')->name('user');
		Route::get('user/{any}', 'AboutAppController@user')->where('any', '.*');
	});
});

// Admin
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
	
	Route::group(['middleware' => 'guest:web-admin', 'guard' => 'web-admin'], function() {
		Route::get('login', 'AuthController@loginPage')->name('login.page');
		Route::post('login', 'AuthController@login')->name('login');
	});


	// Logged In
	Route::group(['middleware' => 'auth:web-admin', 'guard' => 'web-admin'], function() {
		Route::post('logout', 'AuthController@logout')->name('logout');

		Route::get('', 'DashboardController@index')->name('dashboard');
		
		// Admin
		Route::group(['namespace' => 'Admin', 'prefix' => 'admins', 'as' => 'admins.'], function() {
			Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {
				// List
				Route::get('/', 'AdminController@index')->name('index');
				Route::post('/', 'AdminController@ajax')->name('ajax');
				
				Route::get('/new', 'AdminController@edit')->name('create');
				Route::get('/{admin}/edit', 'AdminController@edit')->name('edit');
				Route::post('/store', 'AdminController@update')->name('store');
				Route::post('/{admin}/update', 'AdminController@update')->name('update');
				Route::delete('/{admin}/delete', 'AdminController@delete')->name('delete');
			});
		});
		
		// User
		Route::group(['namespace' => 'User', 'prefix' => 'users', 'as' => 'users.'], function() {
			// User List
			Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
				Route::get('/', 'UserController@index')->name('index');
				Route::post('/', 'UserController@ajax')->name('ajax');
				Route::get('/{user}/detail', 'UserController@detail')->name('detail');
				Route::get('/new', 'UserController@edit')->name('create');
				Route::get('/{user}/edit', 'UserController@edit')->name('edit');
				Route::post('/store', 'UserController@update')->name('store');
				Route::post('/{user}/update', 'UserController@update')->name('update');
				Route::delete('/{user}/delete', 'UserController@delete')->name('delete');
			});
			// User upgrade request
			Route::group(['prefix' => 'upgrade-request', 'as' => 'upgrade-request.'], function() {
				Route::get('/', 'UpgradeRequestController@index')->name('index');
				Route::post('/', 'UpgradeRequestController@ajax')->name('ajax');
				
				Route::get('/{upgradeRequest}/edit', 'UpgradeRequestController@edit')->name('edit');
				Route::post('/{upgradeRequest}/approve', 'UpgradeRequestController@approve')->name('approve');
				Route::post('/{upgradeRequest}/decline', 'UpgradeRequestController@decline')->name('decline');
				Route::delete('/{upgradeRequest}/delete', 'UpgradeRequestController@delete')->name('delete');
			});
			// User verify identity
			Route::group(['prefix' => 'verify-identity', 'as' => 'verify-identity.'], function() {
				Route::get('/', 'VerifyIdentityController@index')->name('index');
				Route::post('/', 'VerifyIdentityController@ajax')->name('ajax');
				
				Route::get('/{user}/edit', 'VerifyIdentityController@edit')->name('edit');
				Route::post('/{user}/approve', 'VerifyIdentityController@approve')->name('approve');
				Route::post('/{user}/decline', 'VerifyIdentityController@decline')->name('decline');
				Route::delete('/{user}/delete', 'VerifyIdentityController@delete')->name('delete');
			});
			// User verify identity
			Route::group(['prefix' => 'pair', 'as' => 'pair.'], function() {
				Route::get('/', 'PairController@index')->name('index');
				Route::post('/', 'PairController@ajax')->name('ajax');
				
				Route::post('/store', 'PairController@update')->name('store');
				Route::post('/{pair}/claim', 'PairController@claim')->name('claim');
				Route::delete('/{pair}/delete', 'PairController@delete')->name('delete');
			});
		});
		// Config
		Route::group(['prefix' => 'config', 'as' => 'config.'], function() {
			Route::get('/', 'ConfigController@index')->name('index');
			Route::post('/', 'ConfigController@ajax')->name('ajax');
			Route::get('/new', 'ConfigController@edit')->name('create');
			Route::get('/{config}/edit', 'ConfigController@edit')->name('edit');
			Route::post('/store', 'ConfigController@update')->name('store');
			Route::post('/{config}/update', 'ConfigController@update')->name('update');
			Route::delete('/{config}/delete', 'ConfigController@delete')->name('delete');
		});
		// Bank
		Route::group(['prefix' => 'bank', 'as' => 'bank.'], function() {
			Route::get('/', 'BankController@index')->name('index');
			Route::post('/', 'BankController@ajax')->name('ajax');
			Route::get('/new', 'BankController@edit')->name('create');
			Route::get('/{bank}/edit', 'BankController@edit')->name('edit');
			Route::post('/store', 'BankController@update')->name('store');
			Route::post('/{bank}/update', 'BankController@update')->name('update');
			Route::delete('/{bank}/delete', 'BankController@delete')->name('delete');
		});
		// Bank Account
		Route::group(['prefix' => 'bank-account', 'as' => 'bank-account.'], function() {
			Route::get('/', 'BankAccountController@index')->name('index');
			Route::post('/', 'BankAccountController@ajax')->name('ajax');
			Route::get('/new', 'BankAccountController@edit')->name('create');
			Route::get('/{bankAccount}/edit', 'BankAccountController@edit')->name('edit');
			Route::post('/store', 'BankAccountController@update')->name('store');
			Route::post('/{bankAccount}/update', 'BankAccountController@update')->name('update');
			Route::delete('/{bankAccount}/delete', 'BankAccountController@delete')->name('delete');
		});
		// Payment
		Route::group(['prefix' => 'payment', 'as' => 'payment.'], function() {
			Route::get('/', 'PaymentController@index')->name('index');
			Route::post('/', 'PaymentController@ajax')->name('ajax');
			Route::get('/new', 'PaymentController@edit')->name('create');
			Route::post('/store', 'PaymentController@update')->name('store');
			Route::get('/statement/{payment}', 'PaymentController@confirmation')->name('confirmation');
			Route::post('/send/{payment}', 'PaymentController@sendEmail')->name('send-email');
		});
		// Top Up
		Route::group(['prefix' => 'top-up', 'as' => 'top-up.'], function() {
			Route::get('/', 'TopUpController@index')->name('index');
			Route::post('/', 'TopUpController@ajax')->name('ajax');
			Route::get('/new', 'TopUpController@edit')->name('create');
			Route::get('/{order}/edit', 'TopUpController@edit')->name('edit');
			Route::post('/store', 'TopUpController@store')->name('store');
			Route::get('/history', 'TopUpController@history')->name('history');
			Route::post('/history', 'TopUpController@historyAjax')->name('history-ajax');
			Route::get('/{order}/history', 'TopUpController@historyView')->name('history-view');
			Route::get('/{order}/confirmation', 'TopUpController@confirmation')->name('confirmation');
			Route::post('/{order}/update', 'TopUpController@update')->name('update');
			Route::post('/{order}/approve', 'TopUpController@approve')->name('approve');
			Route::post('/{order}/recheck', 'TopUpController@recheck')->name('recheck');
			Route::post('/{order}/decline', 'TopUpController@decline')->name('decline');
			Route::get('/{order}/print/{size}', 'TopUpController@print')->name('print');
		});
		// Withdraw
		Route::group(['prefix' => 'withdraw', 'as' => 'withdraw.'], function() {
			Route::get('/', 'WithdrawController@index')->name('index');
			Route::post('/', 'WithdrawController@ajax')->name('ajax');
			Route::get('/{order}/edit', 'WithdrawController@edit')->name('edit');
			Route::get('/history', 'WithdrawController@history')->name('history');
			Route::post('/history', 'WithdrawController@historyAjax')->name('history-ajax');
			Route::get('/{order}/history', 'WithdrawController@historyView')->name('history-view');
			Route::post('/store', 'WithdrawController@update')->name('store');
			Route::post('/{order}/update', 'WithdrawController@update')->name('update');
			Route::post('/{order}/approve', 'WithdrawController@approve')->name('approve');
			Route::post('/{order}/recheck', 'WithdrawController@recheck')->name('recheck');
			Route::post('/{order}/revise', 'WithdrawController@revise')->name('revise');
			Route::post('/{order}/decline', 'WithdrawController@decline')->name('decline');

app/Models/Pair.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Pair extends Model
{
    use SoftDeletes;
    
    protected $fillable = [
        'left_binary_user_id', 'right_binary_user_id', 'leader_user_id', 'leader_package_type', 'is_leader_claimed'
    ];
    
    protected $dates = ['claimed_at', 'created_at', 'updated_at', 'deleted_at'];

    public function leaderUser()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function leftBinaryUser()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function rightBinaryUser()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function order()
    {
        return $this->belongsTo('App\Models\Order');
    }
}

app/Http/Controllers/Admin/User/PairController.php
<?php

namespace App\Http\Controllers\Admin\User;
 
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Exception;
use App\Models\Pair;
use App\Models\User;
use App\Helpers\Managers\PairManager;
use App\Helpers\Enums\PairClaim;
use App\Helpers\Enums\PackageType;
use DataTables;
use Illuminate\Support\Collection;
use Carbon\Carbon;

class PairController extends Controller
{
    public function index(Request $request)
    {
        $statusList = PairClaim::getArray();
        $packageList = PackageType::getArray();

        return view('admin.users.pair.index')
            ->with('statusList', $statusList)
            ->with('packageList', $packageList);
    }

    public function ajax(Request $request)
    {
        $data = Pair::whereNull('claimed_at')->with('leaderUser', 'leftBinaryUser', 'rightBinaryUser')->select('pairs.*');
    	return DataTables::eloquent($data)
            ->filter(function($model) use ($request) {
                if ($request->has('dates') && $request->dates !== null) {
                    $date1 = $request->dates[0];
                    $date2 = new Carbon($request->dates[1].'23:59:59');
                    
                    $model->whereBetween('created_at', [$date1, $date2]);
                }
                if ($request->has('status_enum') && $request->status_enum !== null) {
                    $model->where('is_leader_claimed', $request->status_enum);
                }
                if ($request->has('package_enum') && $request->package_enum !== null) {
                    $model->where('leader_package_type', $request->package_enum);
                }
            }, true)
            ->addColumn('action', function ($model) {
                $str = '<div class="btn-group btn-group-circle">';
                if (!$model->is_leader_claimed) $str .= '<a data-url="'. route('admin.users.pair.claim', ['pair' => $model->id]) .'" class="action" data-toggle="modal" data-target="#modalConfirm" data-table-name="#table" data-method="POST" data-message="Are you sure to <b>CLAIM</b> this pair?"><span class="fas fa-check"></span></a>';
                $str .= '<a data-url="'. route('admin.users.pair.delete', ['pair' => $model->id]) .'" class="action" data-toggle="modal" data-target="#modalConfirm" data-table-name="#table"><span class="far fa-trash-alt"></span></a>';
                $str .= '</div>';
                return $str;
            })
            ->addColumn('package', function ($model) {
                return PackageType::getString($model->leader_package_type);
            })
            ->addColumn('claimed', function ($model) {
                $str = PairClaim::getString($model->is_leader_claimed);
                // if ($model->is_leader_claimed) $str .= ' ('.$model->claimed_at->format('Y-m-d').')';
                return $str;
            })
            ->addColumn('total', function ($model) {
                return number_format(PackageType::getPairingBonus($model->leader_package_type),0,',','.');
            })
            ->editColumn('created_at', function ($model) {
                return $model->created_at->format('j-M-Y');
            })
            ->make(true);
    }

    public function update(Request $request, Pair $pair)
    {
        $validatedData = $request->validate([
            'leader_user_id' => 'required|numeric',
            'left_binary_user_id' => 'required|numeric',
            'right_binary_user_id' => 'required|numeric'
        ]);

        try {
            DB::beginTransaction();
            $pairManager = new PairManager;
            $updatedPair = $pairManager->update($pair, $request->all());
            DB::commit();
            return redirect()->route('admin.users.pair.index')->with('success', 'Pair successfully created');
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return redirect()->back()->with('error', $errorMessage);
        }
    }

    public function claim(Request $request, Pair $pair)
    {
        try {
            DB::beginTransaction();
            $pairManager = new PairManager;
            $updatedPair = $pairManager->claim($request, $pair);
            DB::commit();
            return response()->json(['message' => 'Pair successfully Claimed'], 200);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return response()->json(['message' => $errorMessage], 500);
        }
    }

    public function delete(Request $request, Pair $pair)
    {
        try {
            DB::beginTransaction();
            $pairManager = new PairManager($pair);
            $updatedPair = $pairManager->delete($pair);
            DB::commit();
            return response()->json(['message' => 'Pair successfully Deleted'], 200);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return response()->json(['message' => $errorMessage], 500);
        }
    }
}

resources/views/admin/users/pair/index.blade.php
@extends('templates.admin.master')
@extends('templates.datatables.datatables')

@section('title', 'Pair')
@section('groupName', 'Users')

@section('content')
@include('templates.modal.modal-confirm')
<div class="card card-chart">
    <div class="card-header">
        <h4 class="card-title">Pair</h3>
    </div>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-12 col-md-4">
                <div class="form-group">
                    <label for="filterStatus">Filter Dates</label>
                    {{ Form::text('dates', '', ['class' => 'form-control', 'id' => 'filterDates', 'placeholder' => 'Select Dates']) }}
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="form-group">
                    <label for="filterStatus">Filter Package</label>
                    {{ Form::select('package', $packageList, '', ['class' => 'form-control nullable', 'id' => 'filterPackage', 'placeholder' => 'Show All Package']) }}
                </div>
            </div>
            <div class="col-12 col-md-4">
                <div class="form-group">
                    <label for="filterStatus">Filter Claimed Status</label>
                    {{ Form::select('status', $statusList, '', ['class' => 'form-control nullable', 'id' => 'filterStatus', 'placeholder' => 'Show All Status']) }}
                </div>
            </div>
        </div>
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered table-inside-bordered datatable dataTable" id="table" width="100%">
            <thead>
                <tr>
                    <th rowspan="2">Date</th>
                    <th colspan="5" class="text-center">Leader</th>
                    <th colspan="4" class="text-center">Left Binary</th>
                    <th colspan="4" class="text-center">Right Binary</th>
                    <th rowspan="2">Total</th>
                    <th rowspan="2">Claimed</th>
                    <th rowspan="2">Action</th>
                </tr>
                <tr>
                    <th>Package</th>
                    <th>ID</th>
                    <th>Name</th>
                    <th class="d-none">Leader First Name</th>
                    <th class="d-none">Leader Last Name</th>
                    <th>ID</th>
                    <th>Name</th>
                    <th class="d-none">Left Binary First Name</th>
                    <th class="d-none">Left Binary Last Name</th>
                    <th>ID</th>
                    <th>Name</th>
                    <th class="d-none">Right Binary First Name</th>
                    <th class="d-none">Right Binary Last Name</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th colspan="14" class="text-right">Total:</th>
                    <th colspan="3" class="text-left"></th>
                </tr>
            </tfoot>
            <!-- <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td class="non_searchable d-none"></td>
                    <td class="non_searchable d-none"></td>
                    <td class="non_searchable"></td>
                    <td></td>
                    <td class="non_searchable d-none"></td>
                    <td class="non_searchable d-none"></td>
                    <td></td>
                    <td class="non_searchable d-none"></td>
                    <td class="non_searchable d-none"></td>
                    <td class="non_searchable"></td>
                    <td class="non_searchable"></td>
                </tr>
            </tfoot> -->
            <tbody></tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-12 col-xl-5">
        <div class="card">
        {!! Form::open(['route' => 'admin.users.pair.store', 'method' => 'post', 'class' => 'form-horizontal']) !!}
            <div class="card-header">
                <h4 class="card-title">New Pair</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <label for="leaderId" class="col-5 col-form-label">Leader User Id</label>
                    <div class="col-7">
                        <div class="form-group">
                            {{ Form::text('leader_user_id', '', ['class' => 'form-control', 'id' => 'leaderId', 'placeholder' => 'Leader User Id']) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label for="leftBinaryId" class="col-5 col-form-label">Left Binary User Id</label>
                    <div class="col-7">
                        <div class="form-group">
                            {{ Form::text('left_binary_user_id', '', ['class' => 'form-control', 'id' => 'leftBinaryId', 'placeholder' => 'Left Binary User Id']) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label for="rightBinaryId" class="col-5 col-form-label">Right Binary User Id</label>
                    <div class="col-7">
                        <div class="form-group">
                            {{ Form::text('right_binary_user_id', '', ['class' => 'form-control', 'id' => 'rightBinaryId', 'placeholder' => 'Right Binary User Id']) }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="text-center">
                    <button type="submit" class="btn btn-round btn-info"><i class="fas fa-paper-plane"></i> Submit</button>
                </div>
            </div>
        {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection

@push('pageRelatedCss')
<link rel="stylesheet" type="text/css" href="{{ asset('/css/daterangepicker.css') }}">
@endpush

@push('pageRelatedJs')
<script type="text/javascript" src="{{ asset('js/daterangepicker.js') }}"></script>
<script>
	$(document).ready(function(){
        var filterStatusEnum = null;
        var filterPackageEnum = null;
        var filterDatesEnum = null;

		var table = $('#table').DataTable(
		{
			processing: true,
			serverSide: true,
            responsive: true,
			ajax: {
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				url: '{!! route('admin.users.pair.ajax') !!}',
                data: function(d) { 
                    d.status_enum = filterStatusEnum;
                    d.package_enum = filterPackageEnum;
                    d.dates = filterDatesEnum;
                },
				type: 'POST'
			},
			columns: [
                { data: 'created_at', name: 'pairs.created_at', className: 'text-center' },

                { data: 'package', name: 'package', className: 'text-center', sortable: false, searchable: false },
                { data: 'leader_user.id', name: 'leaderUser.id', className: 'text-center', sortable: false },
                { data: 'leader_user.fullname', className: 'text-center', sortable: false, searchable: false },
                { data: 'leader_user.first_name', name: 'leaderUser.first_name', visible: false },
                { data: 'leader_user.last_name', name: 'leaderUser.last_name', visible: false },

                { data: 'left_binary_user.id', name: 'leftBinaryUser.id', className: 'text-center', sortable: false },
                { data: 'left_binary_user.fullname', className: 'text-center', sortable: false, searchable: false },
                { data: 'left_binary_user.first_name', name: 'leftBinaryUser.first_name', visible: false },
                { data: 'left_binary_user.last_name', name: 'leftBinaryUser.last_name', visible: false },

                { data: 'right_binary_user.id', name: 'rightBinaryUser.id', className: 'text-center', sortable: false },
                { data: 'right_binary_user.fullname', className: 'text-center', sortable: false, searchable: false },
                { data: 'right_binary_user.first_name', name: 'rightBinaryUser.first_name', visible: false },
                { data: 'right_binary_user.last_name', name: 'rightBinaryUser.last_name', visible: false },

                { data: 'total', className: 'text-center', sortable: false, searchable: false },
                { data: 'claimed', className: 'text-center', sortable: false, searchable: false },
                { data: 'action', name: 'action', className: 'text-center', sortable: false, searchable: false },
            ],
            footerCallback: function ( row, data, start, end, display ) {
                var api = this.api(), data;
                
                var intVal = function ( i ) {
                    return typeof i === 'string' ?
                        i.replace(/[.\s]+/g, '')*1 :
                        typeof i === 'number' ?
                            i : 0;
                };

                var rp = function convertToRupiah(angka) {
                    var rupiah = '';		
                    var angkarev = angka.toString().split('').reverse().join('');
                    for(var i = 0; i < angkarev.length; i++) if(i%3 == 0) rupiah += angkarev.substr(i,3)+'.';
                    return 'Rp '+rupiah.split('',rupiah.length-1).reverse().join('');
                }
    
                pageTotal = api
                    .column( 14, { page: 'current'} )
                    .data()
                    .reduce( function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0 );
    
                $(api.column( 0 ).footer()).removeClass('text-center');
                $(api.column( 14 ).footer()).removeClass('text-center');
                $( api.column( 14 ).footer() ).html(
                    rp(pageTotal)
                );
            }
            // initComplete: function () {
            //     this.api().columns().every(function () {
            //         var column = this;
            //         var columnClass = column.footer().className;
            //         var input = $("<input class='form-control' placeholder='Aa...'>");
            //         if (columnClass.indexOf('non_searchable') === -1){
            //             input.appendTo($(column.footer()).empty()).on('input', function () {
            //                 column.search($(this).val(), false, false, true).draw();
            //             });
            //         }
            //     });
            // }
		});
		$(table.table().container()).removeClass('form-inline');

        $('#filterStatus').on('change', function(e) { 
            filterStatusEnum = e.currentTarget.value; 
            table.draw(); 
        }); 

        $('#filterPackage').on('change', function(e) { 
            filterPackageEnum = e.currentTarget.value; 
            table.draw(); 
        });

        $('#filterDates').daterangepicker({
            autoUpdateInput: false,
            autoApply: true,
            locale: {
                format: "DD-MMM-YYYY"
            }
        });

        $('#filterDates').on('apply.daterangepicker', function(ev, picker) {
            $(this).val(picker.startDate.format('DD-MMM-YYYY') + ' - ' + picker.endDate.format('DD-MMM-YYYY'));
            filterDatesEnum = [picker.startDate.format('YYYY-MM-DD'), picker.endDate.format('YYYY-MM-DD')]; 
            table.draw(); 
        });
	});
</script>
@endpush